create table `sync_pre_merge.patients_new_with_ids`
(
  patientid string,
  encounterid string,
  age int64,
  gender string,
  dob date,
  maritalstatus string,
  uid string,
  mobile string,
  alternatemobile string,
  email string,
  remarks string,
  address string,
  centreid int64,
  city string,
  state string,
  country string,
  nationalityid int64,
  pin string,
  insertedon timestamp,
  joiningdate timestamp,
  updateddate timestamp,
  salutation string,
  name string,
  patienthash string,
  deceased bool,
  labname string,
  pid int64,
  eid int64,
  emailid int64,
  mobileid int64,
  alternatemobileid int64,
  remoteid int64
);