CREATE TABLE `sync_merged.numeric` (
    patientid STRING,
    encounterid STRING,
    patientremoteid INT64 NOT NULL,
    bookingid STRING,
    resultdate TIMESTAMP,
    authenticateddate TIMESTAMP,
    specimendate TIMESTAMP,
    biomarkerhash STRING,
    result STRING,
    resultnum FLOAT64,
    comment STRING,
    remarks STRING,
    approvedstatus STRING,
    cancelledflag STRING,
    processing_unit STRING,
    processing_branch STRING,
    indicator INT64,
    centreid INT64,
    biomarkermetaid INT64,
    biomarkercode STRING,
    departmentid INT64,
    labno STRING,
    subdepartment STRING,
    fieldtype STRING,
    entitydoctorid INT64,
    entityreferalid INT64,
    value_type STRING,
    labname STRING,
    insertedon TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updatedon TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) 
cluster BY resultdate;
