CREATE TABLE `sync_merged.patientmerged`
(
  remoteid INT64 NOT NULL,
  labname STRING,
  patientid STRING,
  encounterid STRING,
  salutation STRING,
  name STRING,
  age INT64,
  gender STRING,
  dob DATE,
  maritalstatus STRING,
  uid STRING,
  mobile STRING,
  alternatemobile STRING,
  email STRING,
  city STRING,
  state STRING,
  country STRING,
  pin STRING,
  address STRING,
  remarks STRING,
  centreid INT64,
  nationalityid INT64,
  pid INT64,
  eid INT64,
  emailid INT64,
  mobileid INT64,
  alternatemobileid INT64,
  patientids ARRAY<STRING>,
  encounterids ARRAY<STRING>,
  names ARRAY<STRING>,
  ages ARRAY<INT64>,
  genders ARRAY<STRING>,
  dobs ARRAY<DATE>,
  uids ARRAY<STRING>,
  mobiles ARRAY<STRING>,
  alternatemobiles ARRAY<STRING>,
  emails ARRAY<STRING>,
  centreids ARRAY<INT64>,
  pids ARRAY<INT64>,
  eids ARRAY<INT64>,
  emailids ARRAY<INT64>,
  mobileids ARRAY<INT64>,
  alternatemobileids ARRAY<INT64>,
  deceased BOOL,
  joiningdate TIMESTAMP,
  updateddate TIMESTAMP,
  insertedon TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  updatedon TIMESTAMP DEFAULT CURRENT_TIMESTAMP() 
) cluster by remoteid;