CREATE OR REPLACE TABLE `sync_rawinput.patients_json` 
(
  patientid		STRING,
  encounterid		STRING,
  salutation		STRING,
  sourcename		STRING,
  name		STRING,
  firstname		STRING,
  lastname		STRING,
  gender		STRING,
  age		INTEGER,
  dob		DATE,
  sourceemail		STRING,
  email		STRING,
  sourcealternatemobile		STRING,
  alternatemobile		STRING,
  sourcemobile		STRING,
  mobile		STRING,
  joiningdate		TIMESTAMP,
  updateddate		TIMESTAMP,
  patienthash		STRING,
  upd_dt		TIMESTAMP,
  sourcepatientid		STRING,
  centreid		STRING,
  centrecode		STRING,
  centrename		STRING,
  centrehash		STRING,
  address		STRING,
  address1		STRING,
  address2		STRING,
  city		STRING,
  state		STRING,
  country		STRING,
  pin		STRING,
  remarks		STRING,
  nationality		STRING,
  vipflag		STRING,
  maritalstatus		STRING,
  ptnt_actual_dob_flg		STRING,
  labname		STRING,
  baddata		BOOLEAN,
  baddataremarks		STRING,
  insertedon		TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- CLUSTER BY bookingdate;
