CREATE OR REPLACE TABLE `sync_ctas.patients_lat_values`
(
    patientid INTEGER,
    bookingdate TIMESTAMP,
    entitydoctorid INTEGER,
    centreid INTEGER,
    entityreferalid INTEGER,
    channelid INTEGER,
    remarks STRING,
    visittype STRING,
    insurerparty STRING,
    doctorname STRING,
    patienttypeid INTEGER,
    lastvisitdate DATE,
    nationalityid INTEGER,
    deceased BOOLEAN,
    bmi FLOAT64,
    systolic FLOAT64,
    diastolic FLOAT64,
    bmi_date TIMESTAMP,
    systolic_date TIMESTAMP,
    diastolic_date TIMESTAMP,
    centrename STRING,
    entity_doctorname STRING,
    referalname STRING,
    patienttype STRING,
    channel STRING,
    department STRING,
    nationality STRING,
    encounterid STRING
)